#!/bin/bash
# chkconfig: 345 80 05
# description: Start up Terracotta Management console.
## processname: tmc
##
## user: $RUN_AS_USER
##

RUN_AS_USER="tc_user"
TERRACOTTA_HOME="/opt/terracotta/terracotta-ee/server"
TERRACOTTA_LOGS_HOME="/opt/terracotta/logs"
TMC_HOME="$TERRACOTTA_HOME/../tools/management-console"

# Source function library.
if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser"
else
    SU="/bin/su"
fi

RETVAL=$?
CURRENT_USER=`id -nu`

function getPID() {
    PIDGREP="tools/management-console/jetty-distribution/start.jar"
    PID_CMD=`ps -elf | grep ${PIDGREP} | grep -v grep | awk '{print $4}'`
    echo $PID_CMD
}

function start() {
    RETVAL=1

    if [ -f $TMC_HOME/bin/start-tmc.sh ]; then
        echo "Starting Terracotta Management console..."
        PID=`getPID`
        if [ "x$PID" != "x" ]; then
            echo "Terracotta Management console is already running. PID=$PID"
        else
            cd $TMC_HOME/bin
            if [ "x$CURRENT_USER" != "x$RUN_AS_USER" ]; then
                $SU $RUN_AS_USER -c "/usr/bin/nohup $TMC_HOME/bin/start-tmc.sh >> $TERRACOTTA_LOGS_HOME/nohup-tmc.out 2>&1" &
            else
                /usr/bin/nohup $TMC_HOME/bin/start-tmc.sh >> $TERRACOTTA_LOGS_HOME/nohup-tmc.out 2>&1 &
            fi
            RETVAL=$?
        fi
    fi

    echo -n "Terracotta Management console startup:"
    if [ $RETVAL -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi

    echo
    return $RETVAL
}

function stop() {
    RETVAL=1

    if [ -f $TMC_HOME/bin/stop-tmc.sh ]; then
        echo "Stopping Terracotta Management console..."
        cd $TMC_HOME/bin
        if [ "x$CURRENT_USER" != "x$RUN_AS_USER" ]; then
            $SU $RUN_AS_USER -c "/usr/bin/nohup $TMC_HOME/bin/stop-tmc.sh >> $TERRACOTTA_LOGS_HOME/nohup-tmc.out 2>&1" &
        else
            /usr/bin/nohup $TMC_HOME/bin/stop-tmc.sh >> $TERRACOTTA_LOGS_HOME/nohup-tmc.out 2>&1 &
        fi
        RETVAL=$?
    fi

    echo -n "Terracotta Management console shutdown:"
    if [ $RETVAL -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi

    echo
    return $RETVAL
}

function info() {
    RETVAL=1
    echo -n "Status for Terracotta Management console --> "
    PID=`getPID`
    if [ "x$PID" != "x" ]; then
        echo -n " $PID "
        RETVAL=0
    fi

    if [ $RETVAL -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi

    echo
    return $RETVAL
}

case "$1" in
 start)
    start
     ;;

 stop)
    stop
     ;;
 restart)
    stop
    echo "Waiting 5 seconds before restart..."
    sleep 5
    start
    ;;
 info)
    info
     ;;
 *)
    echo "Usage: $0 {start|stop|restart|info}"
    RETVAL="2"
    ;;
esac

exit $RETVAL
